language: node_js
node_js:
  - node
  - lts/*
cache: npm

jobs:
  include:
    - stage: npm release
      node_js: node
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: API_KEY
        on: deploy-npm-release
