language: node_js
node_js:
  - node
  - lts/*
cache: npm
script:
  - npm run lint
  - npm run test

jobs:
  include:
    - stage: npm release
      node_js: node
      script: npm run build
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$API_KEY"
        skip_cleanup: true
        on:
          tags: true
